### PR TITLE
chore: test in github actions

### PR DESCRIPTION
**Pull request by jbolda**
This adds a test script on PR and push (which is triggered when it is merged into a branch). It will run on ubuntu, mac and windows. There is also a step to cache the node_modules, but this will generally not trigger in PRs (as each PR has it's own cache) unless there a multiple commits. It also sets a timeout to catch situations where the build hangs (like what is currently happening on windows).

This is the first step to address #181. We can enable windows once they pass in CI to keep the builds green.

### CODE REVIEW

**Comment by cowboyd** [comment]
@jbolda Nice! Do we need to do anything else in order to shutdown the CircleCI build? Also, can we name the workflow/job something other than `test/test` maybe `Test Workflow/Run Tests`? I know it's only slightly more descriptive, and we only have 3 checks now, but when the checks start to get into the 20s, it's better to get even that little extra distinction.

**Comment by jbolda** [comment]
It may make sense to revoke their repo access, but that depends how you have things set up. Maybe @taras knows?

I am certainly open to renaming. Perhaps we could set the name as `Package on OS` similar to what we have in https://github.com/thefrontside/bigtest/pull/486.

**Comment by taras** [comment]
> Do we need to do anything else in order to shutdown the CircleCI build?

I think it's just stopping CircleCI from following our repos.

**Comment by jbolda** [comment]
@cowboyd Name has been updated. I currently have this running all the packages in one run. Should we have it split up like in BigTest? Split up will eat up the number of available runners much quicker, but it does make it a little more transparent.

**Comment by cowboyd** [comment]
I think our test run is still fast enough that we can do it in a single run.

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
