### PR TITLE
Fix scroll to behave similar to interactors docs

### PR DESCRIPTION
**Pull request by wKich**
## Motivation

@cowboyd:
> - Whole document needs to scroll, not just when hovered over main content
> - Footer should not be visible when not needed
> - Footer should look like original footer before this PR https://github.com/thefrontside/effection/pull/857 not the “thin” footer with only one link
> - The scroll interaction should be as close to this https://frontside.com/interactors/docs as possible

## Approach

- Removed unnecessary `useAppHtml.tsx`
- Fixed scroll
- Adjust header styles
- Tweak sidebar

### CODE REVIEW

**Comment by cowboyd** [comment]
You're a hero!!

This is a really great first pass. It looks like the burger is a bit close to the content:

image

And then it looks like on the home page, the nav burger is getting pushed off to the right because of the badges being too wide or something.
image

**Comment by wKich** [comment]
> it looks like on the home page, the nav burger is getting pushed off to the right because of the badges being too wide or something.

Nope, the burger is not a part of header content.

Moved it into the header
Screenshot 2023-12-19 at 18 59 17

**Review by cowboyd — APPROVED** [review]
Fantastic work. Looks really smooth and the markup is clean:

**Comment by cowboyd** [comment]
What do we think about the rounded header? It matches the interactors, but I think square might be more 2024

Thoughts?

**Comment by wKich** [comment]
maybe only bottom corners make rounded

**Review by cowboyd — CHANGES_REQUESTED** [review]
Let's just go with square for right now.

**Comment by cowboyd** [comment]
Hmmm.... I think I see what's going on. The nav burger is only on the docs route, so it doesn't work on the home page where there is no sidebar. I think we need to move it back down because it really is part of the guide. 

Effection jpeg

**Review by cowboyd — COMMENTED** [review]
It looks good, although the badges are causing an overflow which makes the page scroll left and right 

Installation  Effection

**Comment by cowboyd** [comment]
@wKich What alternatives to we have to making the header and app wrappers know about what route they're rendering? I'm a bit uncomfortable making the `app.html` aware of what's inside it (`isDocsRoute`) and the header also needing to know about what is being rendered (`showNav`, `showGuides`).

Can we use a form of render props?

**Comment by wKich** [comment]
@cowboyd Could you please check it?

**Comment by cowboyd** [comment]
@wKich Having an `isDocsRoute()` boolean in the head just feels like it's not correct. We're missing an abstraction somewhere.

I think we have a couple of options. One would be to use a context to add navlinks. 

{yield* extraNavlinks([<NavBurger/>]) }

Another, would be to use a render prop for the app html `useAppHtml({ extraNavlinks: [<NavBurger/>] })`

**Comment by wKich** [comment]
Oh, ok. So you mean to pass nav links into header and form them outside?

**Comment by cowboyd** [comment]
Yes. That way the container doesn't need to be aware of the content. Same way that the children are rendered into the body without needing to know what they are.

**Comment by cowboyd** [comment]
Apologies for the delay. I'm going to make sure I get this through because we're almost there. 

The `Guides' link is missing on the docs page (even though it would link back to itself). 

In other words, the links should not "flash" when you navigate between sections of the website as they move from one place to the other. The space should be allocated beforehand, and if you are in the mobile guides, then the burger appears.

Instead of passing the navlinks all through, made even have a "navmenu" property that will allocate that spot?

**Comment by cowboyd** [comment]
@wKich Mainly, what we want to avoid is the menu "flashing" and re-arranging when you click links.

**Comment by cowboyd** [comment]
I see what you mean about it being very squished. What about taking out the `v3` from the header when it is mobile?

**Comment by taras** [comment]
@cowboyd can we go ahead and merge this?

**Comment by cowboyd** [comment]
> @cowboyd can we go ahead and merge this?

It still looks bad on mobile. I think we have to move the v3 from the header on mobile.

**Comment by taras** [comment]
Ok, I’ll take a look.

**Comment by wKich** [comment]
@cowboyd Removed "v3" from the header. Sorry for delay

**Comment by cowboyd** [comment]
Ok, let's rebase and go.

**Review by cowboyd — APPROVED** [review]
I think we're good to go here. Squashing them into a single commit is optional as long as the commits that we have tell a coherent story.

**Pull request merged**
