### PR TITLE
Showing features and benefits on home page

### PR DESCRIPTION
**Pull request by taras**
Preview link https://effection--tm-reorgonize-intro.deno.dev

## Motivation

We want the home page to feature some of the benefits of Effection.

### Fixed proportions of the image and heading in the hero image

image

### Added video embed

image

### Added section about SC

image

### Added section about JavaScript

image

### CODE REVIEW

**Comment by cowboyd** [comment]
Header nav

i noticed that the header links aren’t collapsing into icons.

**Comment by taras** [comment]
I'm re-working the hero section and I'll do fix the header icons too.

**Comment by taras** [comment]
The icons should now show instead of text on small screens.

**Review by cowboyd — APPROVED** [review]
🔥 🔥

**Pull request merged**
