### PR TITLE
Refactor Effection Inspector UI to use Material UI 4

### PR DESCRIPTION
**Pull request by taras**
## Motivation

We're embedding Effection Inspector into Backstage in https://github.com/thefrontside/backstage/pull/24

Not only do we want to create  a version of the inspector that uses material-ui to look pretty in Backstage, but we also need to have a version that can be embedded cleanly into any react app as just a component without having to worry about how to bundle CSS.

## Approach

Replaced CSS with Material UI components

### CODE REVIEW

**Comment by cowboyd** [comment]
Something very odd going on here with `covector preview` https://github.com/thefrontside/effection/runs/6396507855?check_suite_focus=true#step:7:265

Any ideas @jbolda?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/thefrontside/effection">Refactor Effection Inspector UI to use Material UI 4 · thefrontside/effection@42ce7c7</a></strong></div><div>Structured concurrency and effects for JavaScript. Contribute to thefrontside/effection development by creating an account on GitHub.</div></blockquote>

**Comment by taras** [comment]
@cowboyd I think this PR is good to go

**Review by cowboyd — APPROVED** [review]
It looks great to me, and using the preview, I've successfully embedded it into both Backstage as well as a standalone React app with no CSS issues whatsoever.

**Comment by cowboyd** [comment]
@taras previews are not a mandatory check in the branch protection rules, so feel free to merge.

**Pull request merged**
