### PR TITLE
Upgraded to inspector-ui to react-router@6.3.0

### PR DESCRIPTION
**Pull request by taras**
## Motivation

I'm in the process of upgrading inspector-ui to make it embeddable into Backstage. One of the problems that we observed in our integration is that navigating to index page caused the browser to go to root. For example, going from `/inspector/tasks/1`, navigated to `/` instead of `/inspector`. This was caused by the fact that routing was not scoped within the route. We can fix that with relative navigation and nested routes introduced in React Router 6.0.

## Approach

1. Upgraded to react-router@6.3.0. 
2. Defined one root route with 2 child routes as a route object
3. Replaced `<Switch>` with `useRoutes`
4. Refactored to use `element` which allow to eliminate unnecessary wrapper components
5. Refactored to use `Navigate` instead of `Redirect`
6. Created TaskTreePage & TaskPage 

### Possible Drawbacks or Risks

[React Router 6.3 compatibility](https://github.com/backstage/backstage/pull/10450) hasn't been merged yet. It maybe problematic, but I think it should be ok. 

## Learning

[Upgrading from React Router 5](https://reactrouter.com/docs/en/v6/upgrading/v5)

### CODE REVIEW

**Comment by cowboyd** [comment]
What happens when we embed into an app that does not use react router at all?

**Comment by taras** [comment]
That has same behaviour as before. It just works

**Comment by cowboyd** [comment]
> That has same behaviour as before. It just works

Right, but what if the embedding app has its own routing scheme? I'd imagine that this would mess with it.

**Comment by cowboyd** [comment]
@taras Sorry for asking the questions piecemeal. Let me try and lay out everything that I'm thinking about. What happens if:

1. embedded into a `react-router@v5` app?
2. embedded into an app without react router at all?
  * will this hijack the url?
  * Is there a compatibility layer you can wrap around it to adapt to your own routing scheme?

We don't have to do this now, but what would it look like to separate the routing and the components?

**Comment by cowboyd** [comment]
I think we may need to increase the timeout on windows, as I've started to see this fail intermittently.

**Review by cowboyd — APPROVED** [review]

**Comment by taras** [comment]
> embedded into a react-router@v5 app?

I'm not sure if we need to worry about this use case. `react-router@6` has so many nice things that there is no reason to stay on v5 unless you're stuck. 

> embedded into an app without react router at all?

Which router is used is controlled by the router that is rendered in `main.tsx`. We'd need to do some organizing to make it easier to embed the entire thing.

**Pull request merged**
