### PR TITLE
Upgrade nav to include logos and versions

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

Make the project navigation consistent with the website.

## Approach

I applied the styles to the dropdown menu, and changed the logo to be consistent with the menu options. 

Screenshot 2021-11-17 at 17 17 45

### CODE REVIEW

**Review by cowboyd — APPROVED** [review]
Do we need to publish some components from the `frontside.com` website?

**Comment by jorgelainfiesta** [comment]
> Do we need to publish some components from the `frontside.com` website?

what do you mean?

**Comment by cowboyd** [comment]
> > Do we need to publish some components from the `frontside.com` website?
> 
> what do you mean?

😆 I guess I was a little vague. I mean, we have three websites, all using MDX, and all using the same top bar. Maybe we could publish a `@frontside/website` npm package containing these components that could be used in other sites.

```tsx
import { NavBar } from '@frontside/website';

export default function Site() {
  return (
    <App>
      <NavBar/>
      </Body>;
    </App>
  );
}
```

**Comment by jorgelainfiesta** [comment]
Ah yeah, that'd be great! All of our websites use `vanilla-extract` and share a lot of styles. Right now I manually keep them in kind of sync, but have to do it manually.

**Comment by cowboyd** [comment]
This might really help you out then! I don't see it really as a blocker though.

**Comment by jorgelainfiesta** [comment]
It certainly would, I have no idea how to publish stuff but it's a way of learning. I imagine it's not that difficult. Let's merge it for now as is.

**Pull request merged**
