### PR TITLE
Add cause to error.ts

### PR DESCRIPTION
**Pull request by lc-mm**
## Motivation

Maintain a reference to the original error

## Approach

Add the `cause` attribute

### CODE REVIEW

**Comment by cowboyd** [comment]
@lc-mm Before I write a test case for this, have you confirmed that this will work for you by linking it into your codebase and attempting to run it?

**Comment by lc-mm** [comment]
Yes I am running this code in my production app now.

**Review by cowboyd — APPROVED** [review]

**Comment by cowboyd** [comment]
> Yes I am running this code in my production app now.

@lc-mm Fantastic! If I may ask, how long have you been using Effection, and how do you find using it?

**Comment by lc-mm** [comment]
> > Yes I am running this code in my production app now.
> 
> @lc-mm Fantastic! If I may ask, how long have you been using Effection, and how do you find using it?

I chose Effection 2-3 months ago to build out a new feature. I wanted to use generators because I had good experiences in the past using redux saga. So far I have enjoyed using it. I did choose to go with v2 until v3 is out of beta.

On a side note I am using it in react native and did have to add this in order to start using it:

```
window.addEventListener = (x: unknown) => x;
window.removeEventListener = (x: unknown) => x;
```

**Comment by cowboyd** [comment]
Interesting. I'm guessing it's because the main() method? https://github.com/thefrontside/effection/blob/v2/packages/main/src/browser.ts#L33

What would we do to detect the react native app unloading?

Also, please let us know if there's any questions you have, or feedback. We're always looking for ways to improve.

**Comment by lc-mm** [comment]
There is no way that I know of to detect the app closing or unloading, You can detect application states such as foreground or background. When the user closes an app the execution stops without any notice

**Pull request merged**
